name: Python Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest ## En qué maquina ejecutamos este 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Esto es una prueba
        run: | 
          echo "HOLA MUNDO"
      # - name: Install dependencies
      #   run: |
      #     pip install -r requirements.txt
      #
      # - name: Run tests
      #   run: |
      #     pytest -v

